// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sparklee/abc-api/internal/data/ent/schema"
	"github.com/sparklee/abc-api/internal/data/ent/words"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	wordsFields := schema.Words{}.Fields()
	_ = wordsFields
	// wordsDescCreatedAt is the schema descriptor for created_at field.
	wordsDescCreatedAt := wordsFields[3].Descriptor()
	// words.DefaultCreatedAt holds the default value on creation for the created_at field.
	words.DefaultCreatedAt = wordsDescCreatedAt.Default.(time.Time)
	// wordsDescUpdatedAt is the schema descriptor for updated_at field.
	wordsDescUpdatedAt := wordsFields[4].Descriptor()
	// words.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	words.DefaultUpdatedAt = wordsDescUpdatedAt.Default.(time.Time)
}
