// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sparklee/abc-api/internal/data/ent/predicate"
	"github.com/sparklee/abc-api/internal/data/ent/words"
)

// WordsUpdate is the builder for updating Words entities.
type WordsUpdate struct {
	config
	hooks    []Hook
	mutation *WordsMutation
}

// Where appends a list predicates to the WordsUpdate builder.
func (wu *WordsUpdate) Where(ps ...predicate.Words) *WordsUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetGroup sets the "group" field.
func (wu *WordsUpdate) SetGroup(s string) *WordsUpdate {
	wu.mutation.SetGroup(s)
	return wu
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (wu *WordsUpdate) SetNillableGroup(s *string) *WordsUpdate {
	if s != nil {
		wu.SetGroup(*s)
	}
	return wu
}

// SetWord sets the "word" field.
func (wu *WordsUpdate) SetWord(s string) *WordsUpdate {
	wu.mutation.SetWord(s)
	return wu
}

// SetNillableWord sets the "word" field if the given value is not nil.
func (wu *WordsUpdate) SetNillableWord(s *string) *WordsUpdate {
	if s != nil {
		wu.SetWord(*s)
	}
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WordsUpdate) SetCreatedAt(t time.Time) *WordsUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WordsUpdate) SetNillableCreatedAt(t *time.Time) *WordsUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WordsUpdate) SetUpdatedAt(t time.Time) *WordsUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wu *WordsUpdate) SetNillableUpdatedAt(t *time.Time) *WordsUpdate {
	if t != nil {
		wu.SetUpdatedAt(*t)
	}
	return wu
}

// Mutation returns the WordsMutation object of the builder.
func (wu *WordsUpdate) Mutation() *WordsMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WordsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WordsUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WordsUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WordsUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WordsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(words.Table, words.Columns, sqlgraph.NewFieldSpec(words.FieldID, field.TypeInt64))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Group(); ok {
		_spec.SetField(words.FieldGroup, field.TypeString, value)
	}
	if value, ok := wu.mutation.Word(); ok {
		_spec.SetField(words.FieldWord, field.TypeString, value)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(words.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(words.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{words.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WordsUpdateOne is the builder for updating a single Words entity.
type WordsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WordsMutation
}

// SetGroup sets the "group" field.
func (wuo *WordsUpdateOne) SetGroup(s string) *WordsUpdateOne {
	wuo.mutation.SetGroup(s)
	return wuo
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (wuo *WordsUpdateOne) SetNillableGroup(s *string) *WordsUpdateOne {
	if s != nil {
		wuo.SetGroup(*s)
	}
	return wuo
}

// SetWord sets the "word" field.
func (wuo *WordsUpdateOne) SetWord(s string) *WordsUpdateOne {
	wuo.mutation.SetWord(s)
	return wuo
}

// SetNillableWord sets the "word" field if the given value is not nil.
func (wuo *WordsUpdateOne) SetNillableWord(s *string) *WordsUpdateOne {
	if s != nil {
		wuo.SetWord(*s)
	}
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WordsUpdateOne) SetCreatedAt(t time.Time) *WordsUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WordsUpdateOne) SetNillableCreatedAt(t *time.Time) *WordsUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WordsUpdateOne) SetUpdatedAt(t time.Time) *WordsUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wuo *WordsUpdateOne) SetNillableUpdatedAt(t *time.Time) *WordsUpdateOne {
	if t != nil {
		wuo.SetUpdatedAt(*t)
	}
	return wuo
}

// Mutation returns the WordsMutation object of the builder.
func (wuo *WordsUpdateOne) Mutation() *WordsMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WordsUpdate builder.
func (wuo *WordsUpdateOne) Where(ps ...predicate.Words) *WordsUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WordsUpdateOne) Select(field string, fields ...string) *WordsUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Words entity.
func (wuo *WordsUpdateOne) Save(ctx context.Context) (*Words, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WordsUpdateOne) SaveX(ctx context.Context) *Words {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WordsUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WordsUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WordsUpdateOne) sqlSave(ctx context.Context) (_node *Words, err error) {
	_spec := sqlgraph.NewUpdateSpec(words.Table, words.Columns, sqlgraph.NewFieldSpec(words.FieldID, field.TypeInt64))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Words.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, words.FieldID)
		for _, f := range fields {
			if !words.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != words.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Group(); ok {
		_spec.SetField(words.FieldGroup, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Word(); ok {
		_spec.SetField(words.FieldWord, field.TypeString, value)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(words.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(words.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Words{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{words.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
