// Code generated by ent, DO NOT EDIT.

package ent

import (
	"abc/internal/data/ent/words"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordsCreate is the builder for creating a Words entity.
type WordsCreate struct {
	config
	mutation *WordsMutation
	hooks    []Hook
}

// SetGroup sets the "group" field.
func (wc *WordsCreate) SetGroup(s string) *WordsCreate {
	wc.mutation.SetGroup(s)
	return wc
}

// SetWord sets the "word" field.
func (wc *WordsCreate) SetWord(s string) *WordsCreate {
	wc.mutation.SetWord(s)
	return wc
}

// SetCreatedAt sets the "created_at" field.
func (wc *WordsCreate) SetCreatedAt(t time.Time) *WordsCreate {
	wc.mutation.SetCreatedAt(t)
	return wc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wc *WordsCreate) SetNillableCreatedAt(t *time.Time) *WordsCreate {
	if t != nil {
		wc.SetCreatedAt(*t)
	}
	return wc
}

// SetUpdatedAt sets the "updated_at" field.
func (wc *WordsCreate) SetUpdatedAt(t time.Time) *WordsCreate {
	wc.mutation.SetUpdatedAt(t)
	return wc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wc *WordsCreate) SetNillableUpdatedAt(t *time.Time) *WordsCreate {
	if t != nil {
		wc.SetUpdatedAt(*t)
	}
	return wc
}

// SetID sets the "id" field.
func (wc *WordsCreate) SetID(i int64) *WordsCreate {
	wc.mutation.SetID(i)
	return wc
}

// Mutation returns the WordsMutation object of the builder.
func (wc *WordsCreate) Mutation() *WordsMutation {
	return wc.mutation
}

// Save creates the Words in the database.
func (wc *WordsCreate) Save(ctx context.Context) (*Words, error) {
	wc.defaults()
	return withHooks(ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WordsCreate) SaveX(ctx context.Context) *Words {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WordsCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WordsCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WordsCreate) defaults() {
	if _, ok := wc.mutation.CreatedAt(); !ok {
		v := words.DefaultCreatedAt
		wc.mutation.SetCreatedAt(v)
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		v := words.DefaultUpdatedAt
		wc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WordsCreate) check() error {
	if _, ok := wc.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "Words.group"`)}
	}
	if _, ok := wc.mutation.Word(); !ok {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required field "Words.word"`)}
	}
	if _, ok := wc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Words.created_at"`)}
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Words.updated_at"`)}
	}
	return nil
}

func (wc *WordsCreate) sqlSave(ctx context.Context) (*Words, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WordsCreate) createSpec() (*Words, *sqlgraph.CreateSpec) {
	var (
		_node = &Words{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(words.Table, sqlgraph.NewFieldSpec(words.FieldID, field.TypeInt64))
	)
	if id, ok := wc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := wc.mutation.Group(); ok {
		_spec.SetField(words.FieldGroup, field.TypeString, value)
		_node.Group = value
	}
	if value, ok := wc.mutation.Word(); ok {
		_spec.SetField(words.FieldWord, field.TypeString, value)
		_node.Word = value
	}
	if value, ok := wc.mutation.CreatedAt(); ok {
		_spec.SetField(words.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wc.mutation.UpdatedAt(); ok {
		_spec.SetField(words.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WordsCreateBulk is the builder for creating many Words entities in bulk.
type WordsCreateBulk struct {
	config
	err      error
	builders []*WordsCreate
}

// Save creates the Words entities in the database.
func (wcb *WordsCreateBulk) Save(ctx context.Context) ([]*Words, error) {
	if wcb.err != nil {
		return nil, wcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Words, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WordsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WordsCreateBulk) SaveX(ctx context.Context) []*Words {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WordsCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WordsCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}
