// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: abc/v1/word.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type CreateWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *CreateWordRequest) Reset() {
	*x = CreateWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordRequest) ProtoMessage() {}

func (x *CreateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordRequest.ProtoReflect.Descriptor instead.
func (*CreateWordRequest) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type CreateWordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word *Word `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *CreateWordReply) Reset() {
	*x = CreateWordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWordReply) ProtoMessage() {}

func (x *CreateWordReply) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWordReply.ProtoReflect.Descriptor instead.
func (*CreateWordReply) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWordReply) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type UpdateWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *UpdateWordRequest) Reset() {
	*x = UpdateWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordRequest) ProtoMessage() {}

func (x *UpdateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateWordRequest) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type UpdateWordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word *Word `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *UpdateWordReply) Reset() {
	*x = UpdateWordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordReply) ProtoMessage() {}

func (x *UpdateWordReply) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordReply.ProtoReflect.Descriptor instead.
func (*UpdateWordReply) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWordReply) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type DeleteWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteWordRequest) Reset() {
	*x = DeleteWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordRequest) ProtoMessage() {}

func (x *DeleteWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordRequest.ProtoReflect.Descriptor instead.
func (*DeleteWordRequest) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWordReply) Reset() {
	*x = DeleteWordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWordReply) ProtoMessage() {}

func (x *DeleteWordReply) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWordReply.ProtoReflect.Descriptor instead.
func (*DeleteWordReply) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{6}
}

type GetWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWordRequest) Reset() {
	*x = GetWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordRequest) ProtoMessage() {}

func (x *GetWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordRequest.ProtoReflect.Descriptor instead.
func (*GetWordRequest) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{7}
}

func (x *GetWordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word *Word `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *GetWordReply) Reset() {
	*x = GetWordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordReply) ProtoMessage() {}

func (x *GetWordReply) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordReply.ProtoReflect.Descriptor instead.
func (*GetWordReply) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{8}
}

func (x *GetWordReply) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type ListWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWordRequest) Reset() {
	*x = ListWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordRequest) ProtoMessage() {}

func (x *ListWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordRequest.ProtoReflect.Descriptor instead.
func (*ListWordRequest) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{9}
}

type ListWordReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*Word `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *ListWordReply) Reset() {
	*x = ListWordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abc_v1_word_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordReply) ProtoMessage() {}

func (x *ListWordReply) ProtoReflect() protoreflect.Message {
	mi := &file_abc_v1_word_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordReply.ProtoReflect.Descriptor instead.
func (*ListWordReply) Descriptor() ([]byte, []int) {
	return file_abc_v1_word_proto_rawDescGZIP(), []int{10}
}

func (x *ListWordReply) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_abc_v1_word_proto protoreflect.FileDescriptor

var file_abc_v1_word_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x62, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x30, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x40, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x37, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02,
	0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x32, 0xe4, 0x03,
	0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a,
	0x01, 0x2a, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x63, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x3a,
	0x01, 0x2a, 0x1a, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x60, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x10, 0x2a, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x12, 0x57, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x55, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x62, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x62, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x6c, 0x65, 0x65, 0x2f, 0x61, 0x62, 0x63, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x62, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_abc_v1_word_proto_rawDescOnce sync.Once
	file_abc_v1_word_proto_rawDescData = file_abc_v1_word_proto_rawDesc
)

func file_abc_v1_word_proto_rawDescGZIP() []byte {
	file_abc_v1_word_proto_rawDescOnce.Do(func() {
		file_abc_v1_word_proto_rawDescData = protoimpl.X.CompressGZIP(file_abc_v1_word_proto_rawDescData)
	})
	return file_abc_v1_word_proto_rawDescData
}

var file_abc_v1_word_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_abc_v1_word_proto_goTypes = []any{
	(*Word)(nil),              // 0: api.abc.v1.Word
	(*CreateWordRequest)(nil), // 1: api.abc.v1.CreateWordRequest
	(*CreateWordReply)(nil),   // 2: api.abc.v1.CreateWordReply
	(*UpdateWordRequest)(nil), // 3: api.abc.v1.UpdateWordRequest
	(*UpdateWordReply)(nil),   // 4: api.abc.v1.UpdateWordReply
	(*DeleteWordRequest)(nil), // 5: api.abc.v1.DeleteWordRequest
	(*DeleteWordReply)(nil),   // 6: api.abc.v1.DeleteWordReply
	(*GetWordRequest)(nil),    // 7: api.abc.v1.GetWordRequest
	(*GetWordReply)(nil),      // 8: api.abc.v1.GetWordReply
	(*ListWordRequest)(nil),   // 9: api.abc.v1.ListWordRequest
	(*ListWordReply)(nil),     // 10: api.abc.v1.ListWordReply
}
var file_abc_v1_word_proto_depIdxs = []int32{
	0,  // 0: api.abc.v1.CreateWordReply.word:type_name -> api.abc.v1.Word
	0,  // 1: api.abc.v1.UpdateWordReply.word:type_name -> api.abc.v1.Word
	0,  // 2: api.abc.v1.GetWordReply.word:type_name -> api.abc.v1.Word
	0,  // 3: api.abc.v1.ListWordReply.words:type_name -> api.abc.v1.Word
	1,  // 4: api.abc.v1.WordService.CreateWord:input_type -> api.abc.v1.CreateWordRequest
	3,  // 5: api.abc.v1.WordService.UpdateWord:input_type -> api.abc.v1.UpdateWordRequest
	5,  // 6: api.abc.v1.WordService.DeleteWord:input_type -> api.abc.v1.DeleteWordRequest
	7,  // 7: api.abc.v1.WordService.GetWord:input_type -> api.abc.v1.GetWordRequest
	9,  // 8: api.abc.v1.WordService.ListWord:input_type -> api.abc.v1.ListWordRequest
	2,  // 9: api.abc.v1.WordService.CreateWord:output_type -> api.abc.v1.CreateWordReply
	4,  // 10: api.abc.v1.WordService.UpdateWord:output_type -> api.abc.v1.UpdateWordReply
	6,  // 11: api.abc.v1.WordService.DeleteWord:output_type -> api.abc.v1.DeleteWordReply
	8,  // 12: api.abc.v1.WordService.GetWord:output_type -> api.abc.v1.GetWordReply
	10, // 13: api.abc.v1.WordService.ListWord:output_type -> api.abc.v1.ListWordReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_abc_v1_word_proto_init() }
func file_abc_v1_word_proto_init() {
	if File_abc_v1_word_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_abc_v1_word_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateWordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteWordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetWordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_abc_v1_word_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListWordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_abc_v1_word_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_abc_v1_word_proto_goTypes,
		DependencyIndexes: file_abc_v1_word_proto_depIdxs,
		MessageInfos:      file_abc_v1_word_proto_msgTypes,
	}.Build()
	File_abc_v1_word_proto = out.File
	file_abc_v1_word_proto_rawDesc = nil
	file_abc_v1_word_proto_goTypes = nil
	file_abc_v1_word_proto_depIdxs = nil
}
